      - name: Prepare executable permissions
        run: |
          chmod +x run-mac.command
          chmod +x setup.sh
          chmod +x start.sh

      - name: Create ZIP package
        run: |
          zip -r SpotFinder-mac.zip . \
            -x "venv/*" \
            -x ".git/*" \
            -x "*/.env" \
            -x "__pycache__/*" \
            -x "*/__pycache__/*"
